"""Create Tables

Revision ID: 65ba01a594f7
Revises: feb2bd133306
Create Date: 2023-09-25 12:33:55.754307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ba01a594f7'
down_revision = 'feb2bd133306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
