"""Create tables

Revision ID: 731ef9ceb542
Revises: db1774695ad9
Create Date: 2023-09-25 19:23:56.673943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731ef9ceb542'
down_revision = 'db1774695ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
