"""Create Tables

Revision ID: 794d9f07505f
Revises: 65ba01a594f7
Create Date: 2023-09-25 12:52:49.074704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794d9f07505f'
down_revision = '65ba01a594f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
