"""Create tables

Revision ID: cc19c7cbef18
Revises: 731ef9ceb542
Create Date: 2023-09-25 19:28:18.977731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc19c7cbef18'
down_revision = '731ef9ceb542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_pizza_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_pizza_association',
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('pizza_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], )
    )
    # ### end Alembic commands ###
