"""Create tables

Revision ID: db1774695ad9
Revises: 76d8512ba320
Create Date: 2023-09-25 19:22:59.141961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1774695ad9'
down_revision = '76d8512ba320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
